# ITERATION (REPETITION) :-
### FOR LOOP / WHILE LOOP :-
'''
THE SAME GROUP OF STATEMENT GETS REPEATED UNTILL THE CONDITION BECOMES FALSE.

STEP - 1 : INITIALIZATION

STEP - 2 : CONDITION

STEP - 3 : UPDATION
'''

for x in [20, 90, 80, 30, 70, 59, 73, 87, 88,59]:
    print(x)